//
// Generated file, do not edit! Created by nedtool 5.6 from messages/eDTUpdate.msg.
//

#ifndef __EDTUPDATE_M_H
#define __EDTUPDATE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../common/Constants.h"
// }}

/**
 * Class generated from <tt>messages/eDTUpdate.msg:24</tt> by nedtool.
 * <pre>
 * packet eDTUpdate
 * {
 *     string displayString = DISPLAY_STR_MSG_GROUP;
 * 
 *     string dt;
 *     int index;
 *     int variable;
 *     double value;
 * 
 *     simtime_t ts;
 * }
 * </pre>
 */
class eDTUpdate : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string displayString;
    ::omnetpp::opp_string dt;
    int index;
    int variable;
    double value;
    ::omnetpp::simtime_t ts;

  private:
    void copy(const eDTUpdate& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const eDTUpdate&);

  public:
    eDTUpdate(const char *name=nullptr, short kind=0);
    eDTUpdate(const eDTUpdate& other);
    virtual ~eDTUpdate();
    eDTUpdate& operator=(const eDTUpdate& other);
    virtual eDTUpdate *dup() const override {return new eDTUpdate(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getDt() const;
    virtual void setDt(const char * dt);
    virtual int getIndex() const;
    virtual void setIndex(int index);
    virtual int getVariable() const;
    virtual void setVariable(int variable);
    virtual double getValue() const;
    virtual void setValue(double value);
    virtual ::omnetpp::simtime_t getTs() const;
    virtual void setTs(::omnetpp::simtime_t ts);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const eDTUpdate& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, eDTUpdate& obj) {obj.parsimUnpack(b);}


#endif // ifndef __EDTUPDATE_M_H

