//
// Generated file, do not edit! Created by nedtool 5.6 from messages/GranularityType.msg.
//

#ifndef __GRANULARITYTYPE_M_H
#define __GRANULARITYTYPE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>messages/GranularityType.msg:16</tt> by nedtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * enum GranularityType
 * {
 *     SYSTEM = 0;
 *     DIMENSION = 1;
 *     VARIABLE = 2;
 * }
 * </pre>
 */
enum GranularityType {
    SYSTEM = 0,
    DIMENSION = 1,
    VARIABLE = 2
};


#endif // ifndef __GRANULARITYTYPE_M_H

