//
// Generated file, do not edit! Created by nedtool 5.6 from messages/DTCommit.msg.
//

#ifndef __DTCOMMIT_M_H
#define __DTCOMMIT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../common/Constants.h"
// }}

/**
 * Class generated from <tt>messages/DTCommit.msg:20</tt> by nedtool.
 * <pre>
 * packet DTCommit
 * {
 *     string displayString = DISPLAY_STR_MSG_GROUP;
 * 
 *     int dt;
 * 
 *     simtime_t ts;
 * }
 * </pre>
 */
class DTCommit : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string displayString;
    int dt;
    ::omnetpp::simtime_t ts;

  private:
    void copy(const DTCommit& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DTCommit&);

  public:
    DTCommit(const char *name=nullptr, short kind=0);
    DTCommit(const DTCommit& other);
    virtual ~DTCommit();
    DTCommit& operator=(const DTCommit& other);
    virtual DTCommit *dup() const override {return new DTCommit(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual int getDt() const;
    virtual void setDt(int dt);
    virtual ::omnetpp::simtime_t getTs() const;
    virtual void setTs(::omnetpp::simtime_t ts);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DTCommit& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DTCommit& obj) {obj.parsimUnpack(b);}


#endif // ifndef __DTCOMMIT_M_H

