//
// Generated file, do not edit! Created by nedtool 5.6 from messages/RemoteUpdate.msg.
//

#ifndef __REMOTEUPDATE_M_H
#define __REMOTEUPDATE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../common/Constants.h"
#include "GranularityType_m.h"
// }}

/**
 * Class generated from <tt>messages/RemoteUpdate.msg:27</tt> by nedtool.
 * <pre>
 * packet RemoteUpdate
 * {
 *     string displayString = DISPLAY_STR_MSG_GROUP;
 * 
 *     string updates;
 *     int granularity \@enum(GranularityType);
 *     int count;
 *     string digest;
 *     int round;
 *     bool isPull;
 * 
 *     simtime_t ts;
 * }
 * </pre>
 */
class RemoteUpdate : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string displayString;
    ::omnetpp::opp_string updates;
    int granularity;
    int count;
    ::omnetpp::opp_string digest;
    int round;
    bool isPull;
    ::omnetpp::simtime_t ts;

  private:
    void copy(const RemoteUpdate& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RemoteUpdate&);

  public:
    RemoteUpdate(const char *name=nullptr, short kind=0);
    RemoteUpdate(const RemoteUpdate& other);
    virtual ~RemoteUpdate();
    RemoteUpdate& operator=(const RemoteUpdate& other);
    virtual RemoteUpdate *dup() const override {return new RemoteUpdate(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getUpdates() const;
    virtual void setUpdates(const char * updates);
    virtual int getGranularity() const;
    virtual void setGranularity(int granularity);
    virtual int getCount() const;
    virtual void setCount(int count);
    virtual const char * getDigest() const;
    virtual void setDigest(const char * digest);
    virtual int getRound() const;
    virtual void setRound(int round);
    virtual bool getIsPull() const;
    virtual void setIsPull(bool isPull);
    virtual ::omnetpp::simtime_t getTs() const;
    virtual void setTs(::omnetpp::simtime_t ts);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RemoteUpdate& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RemoteUpdate& obj) {obj.parsimUnpack(b);}


#endif // ifndef __REMOTEUPDATE_M_H

