//
// Generated file, do not edit! Created by nedtool 5.6 from messages/PullRequest.msg.
//

#ifndef __PULLREQUEST_M_H
#define __PULLREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../common/Constants.h"
#include "GranularityType_m.h"
// }}

/**
 * Class generated from <tt>messages/PullRequest.msg:27</tt> by nedtool.
 * <pre>
 * packet PullRequest
 * {
 *     string displayString = DISPLAY_STR_MSG_GROUP;
 * 
 *     string request;
 *     int round;
 *     simtime_t ts;
 * }
 * </pre>
 */
class PullRequest : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string displayString;
    ::omnetpp::opp_string request;
    int round;
    ::omnetpp::simtime_t ts;

  private:
    void copy(const PullRequest& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PullRequest&);

  public:
    PullRequest(const char *name=nullptr, short kind=0);
    PullRequest(const PullRequest& other);
    virtual ~PullRequest();
    PullRequest& operator=(const PullRequest& other);
    virtual PullRequest *dup() const override {return new PullRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getRequest() const;
    virtual void setRequest(const char * request);
    virtual int getRound() const;
    virtual void setRound(int round);
    virtual ::omnetpp::simtime_t getTs() const;
    virtual void setTs(::omnetpp::simtime_t ts);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PullRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PullRequest& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PULLREQUEST_M_H

