//
// Generated file, do not edit! Created by nedtool 5.6 from messages/Read.msg.
//

#ifndef __READ_M_H
#define __READ_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../common/Constants.h"
// }}

/**
 * Class generated from <tt>messages/Read.msg:24</tt> by nedtool.
 * <pre>
 * packet Read
 * {
 *     string displayString = DISPLAY_STR_MSG_GROUP;
 * 
 *     int variable;
 *     double value;
 * 
 *     simtime_t ts;
 * }
 * </pre>
 */
class Read : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string displayString;
    int variable;
    double value;
    ::omnetpp::simtime_t ts;

  private:
    void copy(const Read& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Read&);

  public:
    Read(const char *name=nullptr, short kind=0);
    Read(const Read& other);
    virtual ~Read();
    Read& operator=(const Read& other);
    virtual Read *dup() const override {return new Read(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual int getVariable() const;
    virtual void setVariable(int variable);
    virtual double getValue() const;
    virtual void setValue(double value);
    virtual ::omnetpp::simtime_t getTs() const;
    virtual void setTs(::omnetpp::simtime_t ts);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Read& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Read& obj) {obj.parsimUnpack(b);}


#endif // ifndef __READ_M_H

